development:
  adapter: postgresql
  encoding: unicode
  database: alikaragoz_development
  host: localhost
  pool: 5
  username: alikaragoz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: alikaragoz_test
  host: localhost
  pool: 5
  username: alikaragoz
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: alikaragoz_production
  host: localhost
  pool: 5
  username: alikaragoz
  password:
